/*
Enter your query here.
*/
SELECT COMPANY.COMPANY_CODE,MAX(COMPANY.FOUNDER),
    COUNT(DISTINCT(LEAD_MANAGER.LEAD_MANAGER_CODE)),
    COUNT(DISTINCT(SENIOR_MANAGER.SENIOR_MANAGER_CODE)),
    COUNT(DISTINCT(MANAGER.MANAGER_CODE)),
    COUNT(DISTINCT(EMPLOYEE.EMPLOYEE_CODE))
FROM COMPANY,LEAD_MANAGER,SENIOR_MANAGER,MANAGER,EMPLOYEE
WHERE COMPANY.COMPANY_CODE=LEAD_MANAGER.COMPANY_CODE
AND LEAD_MANAGER.LEAD_MANAGER_CODE=SENIOR_MANAGER.LEAD_MANAGER_CODE
AND SENIOR_MANAGER.SENIOR_MANAGER_CODE=MANAGER.SENIOR_MANAGER_CODE
AND MANAGER.MANAGER_CODE=EMPLOYEE.MANAGER_CODE
GROUP BY COMPANY.COMPANY_CODE
ORDER BY COMPANY.COMPANY_CODE ASC;

SELECT c.COMPANY_CODE,
    MAX(c.FOUNDER),
    COUNT(DISTINCT e.LEAD_MANAGER_CODE),
    COUNT(DISTINCT e.SENIOR_MANAGER_CODE),
    COUNT(DISTINCT e.MANAGER_CODE),
    COUNT(DISTINCT e.EMPLOYEE_CODE)
FROM COMPANY c , EMPLOYEE e
WHERE c.COMPANY_CODE = e.COMPANY_CODE
GROUP BY c.COMPANY_CODE
ORDER BY c.COMPANY_CODE;