-- 코드를 입력하세요
SELECT AI.ANIMAL_ID,AI.NAME
FROM ANIMAL_INS AI,ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID=AO.ANIMAL_ID
ORDER BY AO.DATETIME-AI.DATETIME DESC
LIMIT 2;

SELECT AI.ANIMAL_ID,AI.NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID=AO.ANIMAL_ID
ORDER BY AO.DATETIME-AI.DATETIME DESC
LIMIT 2;