-- 코드를 입력하세요
SELECT CART_G.CART_ID 
FROM (SELECT CART_ID,GROUP_CONCAT(NAME) NAMES
     FROM CART_PRODUCTS
     GROUP BY CART_ID) CART_G
WHERE NAMES REGEXP ".*(Milk).*"
AND NAMES REGEXP ".*(Yogurt).*"
ORDER BY CART_G.CART_ID;